---
- name: Authenticate with Patch Manager Plus
  hosts: localhost
  gather_facts: false
  vars:
    pmp_base_url: "https://example.com/api/1.3/desktop/authentication"
    pmp_username: "{{ lookup('env', 'PMP_USERNAME') }}"
    pmp_password: "{{ lookup('env', 'PMP_PASSWORD') }}"
    pmp_auth_type: "{{ lookup('env', 'PMP_AUTH_TYPE', default='local_authentication') }}"
    pmp_domain_name: "{{ lookup('env', 'PMP_DOMAIN_NAME') }}"
  tasks:
    - name: Generate base64 encoded password
      set_fact:
        pmp_password_base64: "{{ pmp_password | b64encode }}"

    - name: Obtain auth token
      uri:
        url: "{{ pmp_base_url }}?username={{ pmp_username }}&password={{ pmp_password_base64 }}&auth_type={{ pmp_auth_type }}"
        method: GET
        headers:
          Accept: "application/json"
      register: pmp_auth_response

    - name: Extract auth token from response
      set_fact:
        pmp_auth_token: "{{ pmp_auth_response.json.message_response.auth_token }}"

    - name: Set auth token header for subsequent requests
      set_fact:
        pmp_headers:
          Authorization: "{{ pmp_auth_token }}"

# Note: This dev playbook assumes that the PMP username and password are stored in environment variables 
# PMP_USERNAME and PMP_PASSWORD, respectively. The pmp_auth_type variable is set to local_authentication by 
# default, but can be set to ad_authentication if necessary. If ad_authentication is used, the PMP_DOMAIN_NAME 
# environment variable should also be set.
